services:
  customer-service:
    build: ./services/customer-service
    container_name: customer-container
    ports:
      - "3000:3000"

  employee-service:
    build: ./services/employee-service
    container_name: employee-container
    ports:
      - "3001:3001"
