version: 1.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<EMPLOYEE_SERVICE_TASK_DEFINITION_ARN>"
        LoadBalancerInfo:
          ContainerName: "employee-service"
          ContainerPort: 3001
