version: 1.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<CUSTOMER_SERVICE_TASK_DEFINITION_ARN>"
        LoadBalancerInfo:
          ContainerName: "customer-service"
          ContainerPort: 3000
